### PR TITLE
make findBack more correct for greedy regexps

### PR DESCRIPTION
**Pull request by idupree**
Previously, (pretend "|" is range position), "aaaa|aa" findBack(/a+/)
would not be able to find anything because the regexp would
always go past the current location by mistake.  Luckily there
is a workaround.  /a+(?=.{2})/ says only to find matches followed
by at least two characters (two being the number of remaining
characters after the current range).  The full workaround'ed regex
is /(?:a+)(?=[\s\S]{2})/g, because:
    - /./ can't match newlines in JS,
    - the original pattern might have /|/ that we need to
        parenthesize in order to add a suffix to the full
        original pattern.

Meanwhile, this change allows to simplify the forward-search
code as well.  This simplification makes findprimitive
also work with greedy regex for searches on a range whose
bounds[1] < text.length (relevant if we ever expose that capability).

### CODE REVIEW

**Comment by dwachss** [comment]
Thanks for all your work on this. I'm going to have to take some time to think about this.

**Comment by idupree** [comment]
I appreciate you thinking on this one!

It was tempting to run the caller's regex on a substring of range.all().  However that has the downside that forward lookahead in the regex will do the wrong thing (`(?=`, `(?!`, `$`, `\b`, `\B`).  If you find a better way to do this than regex followed by lookahead N characters, I'd love to hear it.  If you find out that my method is wrong or intolerably slow, I would also appreciate finding out.  The following link is how I chose `[\s\S]` to match any code unit: http://stackoverflow.com/a/16119722

Question I have not resolved: should the "aaaaaa" /a+/ example select just the one "a" previous to the cursor, or select all the "a"s previous to the cursor?  I think normally the latter option, which is analogous to a backwards greediness, is preferred.[1] I can implement the backwards greediness by changing findprimitiveback to only update lastMatch to the new match if the new match's endpoint (index+length) is after the old lastMatch's endpoint.

[1] Though occasionally the non-greedy one would be preferred, just as people sometimes use `*?`. I haven't thought of a way to examine the regex to determine the preferred greediness level, considering that it could contain both greedy and lazy repetitions, like this attempt at matching both `//` and `/*` comments: `/[/][/].*$|[/][*][\s\S]*?[*][/]/m`

**Comment by dwachss** [comment]
It's been 5 years, but I'm finally going back to update bililiteRange. I like your solution to forcing the search to be in a given range, and it simplifies the code a lot. I've completely changed the API for `find` (it's now `bounds(/foo/)`) but I incorporated your code. The updates are on branch "edge" and I will close this when I merge that into "master".

**Comment by dwachss** [comment]
In answer to your last question about greedy vs. nongreedy backwards searches, I am using global RegExps that set `lastIndex` to the end of the match, which makes them greedy. If someone wants something fancier, then will have to do it themselves.

**Pull request closed without merging**
